version: '3.8'
services:
  db:
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=50
    image: postgres:14.1-alpine
    #    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=pass
    ports:
      - '5455:5432'
#    volumes:
#      - ./db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
