server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5455/postgres
    username: root
    password: pass
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    # todo: find a better way of logging SQL
    show-sql: true
  liquibase:
    change-log: db/changelog-master.xml

logging:
  level:
    com.booster.server: DEBUG
